# Generated by Django 4.1.4 on 2022-12-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("sud-ouest", "Sud Ouest"),
                    ("bordeaux", "Bordeaux"),
                    ("bourgogne", "Bourgogne"),
                    ("val-de-loire", "Val De Loire"),
                    ("languedoc-roussillon", "Languedoc Roussillon"),
                    ("vallée-du-rhône", "Vallée Du Rhône"),
                    ("savoie", "Savoie"),
                    ("corse", "Corse"),
                    ("beaujolais", "Beaujolais"),
                    ("alsace-lorraine", "Alsace Lorraine"),
                    ("provence", "Provence"),
                    ("centre-loire", "Centre Loire"),
                    ("jura", "Jura"),
                    ("champagne", "Champagne"),
                ],
                default="bordeaux",
                max_length=40,
            ),
        ),
    ]
