# Generated by Django 4.1.4 on 2022-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vins", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("abouriou", "Abouriou"),
                    ("bourboulenc", "Bourboulenc"),
                    ("braucol", "Braucol"),
                    ("cabernet", "Cabernet"),
                    ("cabernet-Franc", "Cabernet Franc"),
                    ("cabernet-Sauvignon", "Cabernet Sauvignon"),
                    ("caladoc", "Caladoc"),
                    ("camaralet", "Camarale"),
                    ("carignan", "Carignan"),
                    ("carignan-blanc", "Carignan Blanc"),
                    ("chardonnay", "Chardonnay"),
                    ("chenin", "Chenin"),
                    ("chenin-blanc", "Chenin Blanc"),
                    ("cinsault", "Cinsault"),
                    ("clairette", "Clairette"),
                    ("colombard", "Colombard"),
                    ("courbu", "Courbu"),
                    ("egiodola", "Egiodola"),
                    ("gamay", "Gamay"),
                    ("grenache", "Grenache"),
                    ("grenache-blanc", "Grenache Blanc"),
                    ("grenache-gris", "Grenache Gris"),
                    ("grenache-noir", "Grenache Noir"),
                    ("gros-Manseng", "Gros Manseng"),
                    ("loin-de-l-oeil", "Loin De L Oeil"),
                    ("macabeu", "Macabeu"),
                    ("malbec", "Malbec"),
                    ("marsanne", "Marsanne"),
                    ("marselan", "Marselan"),
                    ("mauzac", "Mauzac"),
                    ("melon-de-Bourgogne", "Melon De Bourgogne"),
                    ("merlot", "Merlot"),
                    ("meunier", "Meunier"),
                    ("mourvèdre", "Mourvèdre"),
                    ("muscadelle", "Muscadelle"),
                    ("muscat-petits-grains", "Muscat Petits Grains"),
                    ("negrette", "Negrette"),
                    ("petit-Courbu", "Petit Courbu"),
                    ("petit-Manseng", "Petit Manseng"),
                    ("petit-Verdot", "Petit Verdot"),
                    ("pineau-dAunis", "Pineau D Aunis"),
                    ("pinot-noir", "Pinot Noir"),
                    ("poulsard", "Poulsard"),
                    ("rolle", "Rolle"),
                    ("roussanne", "Roussanne"),
                    ("sauvignon", "Sauvignon"),
                    ("sauvignon-blanc", "Sauvignon Blanc"),
                    ("sauvignon-gris", "Sauvignon Gris"),
                    ("savagnin", "Savagnin"),
                    ("syrah", "Syrah"),
                    ("sémillon", "Sémillon"),
                    ("tannat", "Tannat"),
                    ("tressailler", "Tressailler"),
                    ("ugni-blanc", "Ugni Blanc"),
                    ("vermentino", "Vermentino"),
                    ("viognier", "Viognier"),
                ],
                default="merlot",
                max_length=30,
            ),
        ),
    ]
