# Generated by Django 4.1.4 on 2023-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vin',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
